# trend_harvester.yaml (Compound Flow)
version: "0.2.1"
metadata:
  name: "viral-content-generator"
  flow_type: "compound"

inputs:
  topic:
    type: string
    description: "Topic of the content"
    required: true
    example: "fashion"

workflow:
  trend_fetch:
    type: "composio"
    action: "SCRAPE_SOCIAL"
    inputs:
      platform: ${inputs.platform}

  analysis:
    depends_on: [trend_fetch]
    type: "elemental"
    flow_name: "core/trend-analysis"

  ideation:
    depends_on: [analysis]
    type: "custom"
    prompt: |
      Generate 5 content ideas combining:
      Trends: {analysis.top_trends}
      Platform: {inputs.platform}
